name: CMake

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Windows 10 SDK Action
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
      with:
        sdk-version: 22621

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout submodules
      shell: bash
      run: git submodule update --init --recursive

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build -A Win32 -T v143

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -A Win32 -T v143

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config RelWithDebInfo

    - name: Save output
      uses: actions/upload-artifact@v3
      with:
        path: ${{runner.workspace}}/GWToolboxpp/bin/RelWithDebInfo/
